stages:
  - build
  
ci_build_release_linux:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - make
  tags:
    - linux
    - non-docker

ci_build_and_test_linux:
  stage: build
  script:
    - mkdir build && cd build
    - cmake .. -DFEATURE_POST_BUILD_UNITTEST=ON -DFEATURE_HBM_HARDWARE=OFF -DFEATURE_GCOV=ON
    - make && make test
    - lcov --directory . --capture --output-file libhbm.cov
    - lcov --list libhbm.cov
  coverage: '\s*lines\.*:\s*([\d\.]+%)'
  tags:
    - linux
    - non-docker

#ci_build_and_test_windows:
#  stage: build
#  script:
#    -
#  tags:
#    - windows
