image: gitlab.hbm.com:5555/share/jet:latest

stages:
  - build
  
ci_build_linux:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DFEATURE_POST_BUILD_UNITTEST=ON -DFEATURE_HBM_HARDWARE=OFF -DFEATURE_TOOLS=ON ..
    - make -j
    - ctest --output-on-failure
  tags:
    - docker

#ci_build_and_test_windows:
#  stage: build
#  script:
#    -
#  tags:
#    - windows
