before_script:
    - echo "Es geht Los @@@@"

stages:
  - build
  - test

ci_build:
  stage: build
  script:
    - mkdir build && cd build && cmake .. && make
  tags:
    - linux

ci_test:
  stage: test
  script:
    - cd build && make test
  tags:
    - linux
