stages:
  - build
  
ci_build_linux:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DFEATURE_POST_BUILD_UNITTEST=ON -DFEATURE_HBM_HARDWARE=OFF -DFEATURE_TOOLS=ON ..
    - make
    - make test
  tags:
    - linux
    - non-docker

#ci_build_and_test_windows:
#  stage: build
#  script:
#    -
#  tags:
#    - windows
