stages:
  - build

ci_build_and_test:
  stage: build
  script:
    - mkdir build && cd build && cmake .. -DFEATURE_POST_BUILD_UNITTEST=ON && make && make test
  tags:
    - linux

doxygen:
  stage: build
  script:
    - doxygen Doxyfile
  tags:
    - linux
